// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewClientHTTPRequester creates a new instance of ClientHTTPRequester. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientHTTPRequester(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientHTTPRequester {
	mock := &ClientHTTPRequester{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ClientHTTPRequester is an autogenerated mock type for the HTTPRequester type
type ClientHTTPRequester struct {
	mock.Mock
}

type ClientHTTPRequester_Expecter struct {
	mock *mock.Mock
}

func (_m *ClientHTTPRequester) EXPECT() *ClientHTTPRequester_Expecter {
	return &ClientHTTPRequester_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type ClientHTTPRequester
func (_mock *ClientHTTPRequester) Close() {
	_mock.Called()
	return
}

// ClientHTTPRequester_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type ClientHTTPRequester_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *ClientHTTPRequester_Expecter) Close() *ClientHTTPRequester_Close_Call {
	return &ClientHTTPRequester_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *ClientHTTPRequester_Close_Call) Run(run func()) *ClientHTTPRequester_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ClientHTTPRequester_Close_Call) Return() *ClientHTTPRequester_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *ClientHTTPRequester_Close_Call) RunAndReturn(run func()) *ClientHTTPRequester_Close_Call {
	_c.Run(run)
	return _c
}

// Request provides a mock function for the type ClientHTTPRequester
func (_mock *ClientHTTPRequester) Request(ctx context.Context, method string, path string, input any, output any) (int, error) {
	ret := _mock.Called(ctx, method, path, input, output)

	if len(ret) == 0 {
		panic("no return value specified for Request")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, any, any) (int, error)); ok {
		return returnFunc(ctx, method, path, input, output)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, any, any) int); ok {
		r0 = returnFunc(ctx, method, path, input, output)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, any, any) error); ok {
		r1 = returnFunc(ctx, method, path, input, output)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClientHTTPRequester_Request_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Request'
type ClientHTTPRequester_Request_Call struct {
	*mock.Call
}

// Request is a helper method to define mock.On call
//   - ctx context.Context
//   - method string
//   - path string
//   - input any
//   - output any
func (_e *ClientHTTPRequester_Expecter) Request(ctx interface{}, method interface{}, path interface{}, input interface{}, output interface{}) *ClientHTTPRequester_Request_Call {
	return &ClientHTTPRequester_Request_Call{Call: _e.mock.On("Request", ctx, method, path, input, output)}
}

func (_c *ClientHTTPRequester_Request_Call) Run(run func(ctx context.Context, method string, path string, input any, output any)) *ClientHTTPRequester_Request_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 any
		if args[3] != nil {
			arg3 = args[3].(any)
		}
		var arg4 any
		if args[4] != nil {
			arg4 = args[4].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *ClientHTTPRequester_Request_Call) Return(n int, err error) *ClientHTTPRequester_Request_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *ClientHTTPRequester_Request_Call) RunAndReturn(run func(ctx context.Context, method string, path string, input any, output any) (int, error)) *ClientHTTPRequester_Request_Call {
	_c.Call.Return(run)
	return _c
}
