packages:
  github.com/borderzero/border0-go/client:
    interfaces:
      HTTPRequester:
        config:
          dir: client/mocks
          pkgname: mocks
          structname: ClientHTTPRequester
          filename: client_http_requester.go
      Requester:
        config:
          dir: listen/mocks
          pkgname: mocks
          structname: APIClientRequester
          filename: api_client_requester.go
