quiet: False
disable-version-string: True
with-expecter: True
outpkg: mocks
packages:
  github.com/borderzero/border0-go/client:
    interfaces:
      HTTPRequester:
        config:
          dir: mocks
          structname: ClientHTTPRequester
          filename: client_http_requester.go
